import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../sanity'
import { Post } from '../typings'
import Link from 'next/link';
import createImageUrlBuilder from '@sanity/image-url'
import urlBuilder from '@sanity/image-url'



interface Props {
  posts: [Post];
}

const Home: NextPage = ({ posts }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>

        {/* All the other content starts here */}

        {/* HERO CONTENT________________________________________________________________ */}







        {/* All the posts starts here */}

        {posts.map(post => (
          // <Link key={post._id} href={`/posts/${post.slug.current}`} >
            <div key={post._id}>
              <div>
                <img src={urlFor(post.mainImage).url()!} alt="" />
              </div>
              <div><h1>{post.title}</h1></div>
              <div><p>{post.description}</p></div>
              <p>{post._publishedAt}</p>
            </div>
          // </Link>
        ))}

        {/* Posts are ending here */}

        {/* Other content starts here */}

      </div>
    </div>
  )
}


// Sanity data fetching starts here

export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    title,
    description,
    publishedAt,
    body,
    mainImage,
    slug,
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    }
  }
};


export default Home
