import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../sanity'
import { Post } from '../typings'
import Link from 'next/link';
import createImageUrlBuilder from '@sanity/image-url'
import urlBuilder from '@sanity/image-url'



interface Props {
  posts: [Post];
}

const Home: NextPage = ({ posts }: Props) => {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {posts.map(post => (
          <Link key={post._id} href={`/posts/${post.slug.current}`} >
            <div>
              <div>
                <img src={
                  urlFor(post.mainImage).url()!
                } alt="" />
              </div>
              <div><h1>{post.title}</h1></div>
              <div><p>{post.description}</p></div>
              <p>{post._createdAt}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}


export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    title,
    description,
    publishedAt,
    body,
    mainImage,
    slug,
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    }
  }
};


export default Home
